// Node.js script to generate an image filename array for the gallery
// Run this script with: node scripts/generateGalleryList.js

const fs = require('fs');
const path = require('path');

const galleryDir = path.join(__dirname, '../public/gallery');
const outputFile = path.join(__dirname, '../src/sections/galleryImages.js');

// Supported image extensions
const exts = ['.jpg', '.jpeg', '.png', '.webp'];

fs.readdir(galleryDir, (err, files) => {
  if (err) {
    console.error('Error reading gallery folder:', err);
    process.exit(1);
  }
  const imageFiles = files.filter(file =>
    exts.includes(path.extname(file).toLowerCase())
  ).sort();

  const jsContent = `// Auto-generated by scripts/generateGalleryList.js\nexport const galleryImages = [\n  ${imageFiles.map(f => `'${f}'`).join(',\n  ')}\n];\n`;

  fs.writeFile(outputFile, jsContent, err => {
    if (err) {
      console.error('Error writing image list file:', err);
      process.exit(1);
    }
    console.log('Gallery image list generated:', outputFile);
  });
});
