// Auto-generated by scripts/generateGalleryList.js
export const galleryImages = [
  'photo1.jpg',
  'photo10.jpg',
  'photo11.jpg',
  'photo12.jpg',
  'photo13.jpg',
  'photo14.jpg',
  'photo15.jpg',
  'photo16.jpg',
  'photo17.jpg',
  'photo18.jpg',
  'photo19.jpg',
  'photo2.jpg',
  'photo20.jpg',
  'photo3.jpg',
  'photo4.jpg',
  'photo5.jpg',
  'photo6.jpg',
  'photo7.jpg',
  'photo8.jpg',
  'photo9.jpg'
];
